[package]
name = "non-fungible-token"
version = "1.1.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "4.1.0-pre.2", features = ["abi"] }
near-contract-standards = { version = "4.1.0-pre.2", features = ["abi"] }
